default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.16.3
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.17
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: v0.0.48
    hooks:
      - id: ty
